version: '3'

networks:
  laravel:
    driver: bridge


services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_docker
    ports:
      - "8080:80"
    tty: true
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_docker
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - /var/www/html/vendor
    ports:
      - "9000:9000"
    networks:
      - laravel

  mysql:
    container_name: db
    restart: always
    image: mysql:latest
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'username'
      MYSQL_PASS: 'password'
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - laravel
